// <auto-generated />
using System;
using Blazor_ApiStatusCheck.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor_ApiStatusCheck.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240716112457_SeedHealthChecksTable")]
    partial class SeedHealthChecksTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor_ApiStatusCheck.Connection.ApiHealthCheck", b =>
                {
                    b.Property<string>("Api__Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Api__Id");

                    b.ToTable("HealthChecks");

                    b.HasData(
                        new
                        {
                            Api__Id = "1",
                            CreatedAt = new DateTime(2024, 7, 16, 14, 24, 56, 778, DateTimeKind.Local).AddTicks(6360),
                            LastChecked = new DateTime(2024, 7, 16, 14, 24, 56, 778, DateTimeKind.Local).AddTicks(6371),
                            Message = "healthy",
                            Name = "Api_1",
                            Status = "healthy",
                            Url = "www.api1.com"
                        },
                        new
                        {
                            Api__Id = "2",
                            CreatedAt = new DateTime(2024, 7, 16, 14, 24, 56, 778, DateTimeKind.Local).AddTicks(6375),
                            LastChecked = new DateTime(2024, 7, 16, 14, 24, 56, 778, DateTimeKind.Local).AddTicks(6376),
                            Message = "degraded",
                            Name = "Api_2",
                            Status = "degraded",
                            Url = "www.api2.com"
                        },
                        new
                        {
                            Api__Id = "3",
                            CreatedAt = new DateTime(2024, 7, 16, 14, 24, 56, 778, DateTimeKind.Local).AddTicks(6377),
                            LastChecked = new DateTime(2024, 7, 16, 14, 24, 56, 778, DateTimeKind.Local).AddTicks(6378),
                            Message = "unhealthy",
                            Name = "Api_3",
                            Status = "unhealthy",
                            Url = "www.api3.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
